language: bash

before_script:
    - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx

script:
    - bash hello_travis.sh
    - bash gen_ssh_keys.sh
    - bash ubuntu_deeplearning_setup.sh