language: bash
matrix:
  include:
      dist: xenial
      sudo: true
    
before_script:
    - sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx

script:
    - bash hello_travis.sh
    - bash gen_ssh_keys.sh
